export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
/* FILTER */
export const FILTER_PRODUCTS_BY_SIZE = "FILTER_PRODUCTS_BY_SIZE";
export const ORDER_PRODUCTS_BY_PRICE = "ORDER_PRODUCTS_BY_PRICE";
/* CART ITEMS */
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

/*  ORDER ITEMS */
export const CLEAR_CART = "CLEAR_CART";
export const CLEAR_ORDER = "CLEAR_ORDER";
export const CREATE_ORDER = "CREATE_ORDER";
